# Generated by Django 4.1.2 on 2022-11-04 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Enter First Name', max_length=400)),
                ('last_name', models.CharField(default='Enter Last Name', max_length=400)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Song Title', max_length=400)),
                ('date_released', models.DateTimeField(default=datetime.datetime(2022, 11, 4, 17, 30, 1, 699782))),
                ('likes', models.CharField(default='DEFAULT VALUE', max_length=400)),
                ('artiste_identity', models.CharField(default='', max_length=400)),
                ('Artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musicapp.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Content')),
                ('lyrics_title', models.CharField(default='', max_length=200)),
                ('Song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musicapp.song')),
            ],
        ),
    ]
